#! /bin/bash

if [ $# -eq 1 ]; then
	git pull --rebase &> /dev/null
	git tag -a $1 -m "Version $1 released" &> /dev/null;
	rm -Rf build/* &> /dev/null;
	cd build &> /dev/null;
	cmake -DVERSION_UPDATE_FROM_GIT=true .. &> /dev/null;
	cd .. &> /dev/null;
	git add * &> /dev/null;
	git commit -a -m "Version $1 released" &> /dev/null;

	# Delete tag to be readded with VERSION autogenerated file
	git tag -d $1 &> /dev/null;
	git tag -a $1 -m "Version $1 released" &> /dev/null;
	git push origin $1 &> /dev/null;
	echo "Version $1 released and pushed";
else
	echo "Only 1 argument is expected and should be version string!";
fi
