if(UNIX)
	add_compile_options(-fvisibility=hidden -fvisibility-inlines-hidden)
	set(CMAKE_CXX_FLAGS_DEBUG_INIT		"-g -ggdb -Wall -Wextra")
else()
	set(CMAKE_CXX_FLAGS_RELEASE_INIT	"/O2 /EHsc")
endif()
