# Encoder support
# Video
option(WITH_AV1				"Enable AV1 codec"					ON)
option(WITH_H264			"Enable H264 codec"					ON)
option(WITH_H265			"Enable HEVC/H265 codec"			ON)
option(WITH_MPEG2			"Enable MPEG2 codec"				ON)
option(WITH_RAV1E			"Enable RAV1E codec"				ON)
option(WITH_VPX				"Enable VPX codec"					ON)
option(WITH_XVID			"Enable XVID codec"					ON)
# Audio
option(WITH_AAC				"Enable AAC codec"					ON)
option(WITH_AC3				"Enable AC3 codec"					ON)
option(WITH_DTS				"Enable DTS codec"					ON)
option(WITH_EAC3			"Enable EAC3 codec"					ON)
option(WITH_FDK_AAC			"Enable FDK_AAC codec"				ON)
option(WITH_FLAC			"Enable FLAC codec"					ON)
option(WITH_MP3				"Enable MP3 codec"					ON)
option(WITH_OPUS			"Enable OPUS codec"					ON)
option(WITH_VORBIS			"Enable VORBIS codec"				ON)

# Codec configuration
# Video
if (WITH_AV1)
	message(STATUS "AV1 codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AV1)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/av1.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/av1.hxx)
else()
	message(STATUS "AV1 codec disabled")
endif()
if (WITH_H264)
	message(STATUS "H264 codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_H264)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h264.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h264.hxx)
else()
	message(STATUS "H264 codec disabled")
endif()
if (WITH_H265)
	message(STATUS "HEVC/H265 codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_H265)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h265.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h265.hxx)
else()
	message(STATUS "HEVC/H265 codec disabled")
endif()
if (WITH_MPEG2)
	message(STATUS "MPEG2 codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_MPEG2)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/mpeg2.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/mpeg2.hxx)
else()
	message(STATUS "MPEG2 codec disabled")
endif()
if (WITH_RAV1E)
	message(STATUS "RAV1E codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_RAV1E)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/rav1e.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/rav1e.hxx)
else()
	message(STATUS "RAV1E codec disabled")
endif()
if (WITH_VPX)
	message(STATUS "VPX codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_VPX)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/vpx.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/vpx.hxx)
else()
	message(STATUS "VPX codec disabled")
endif()
if (WITH_XVID)
	message(STATUS "XVID codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_XVID)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/xvid.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/xvid.hxx)
else()
	message(STATUS "XVID codec disabled")
endif()

# Audio
if (WITH_AAC)
	message(STATUS "AAC codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AAC)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/aac.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/aac.hxx)
else()
	message(STATUS "AAC codec disabled")
endif()
if (WITH_AC3)
	message(STATUS "AC-3 codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AC3)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/ac3.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/ac3.hxx)
	else()
	message(STATUS "AC-3 codec disabled")
endif()
if (WITH_DTS)
	message(STATUS "DTS codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_DTS)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/dts.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/dts.hxx)
else()
	message(STATUS "DTS codec disabled")
endif()
if (WITH_EAC3)
	message(STATUS "EAC-3 codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_EAC3)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/eac3.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/eac3.hxx)
else()
	message(STATUS "EAC-3 codec disabled")
endif()
if (WITH_FDK_AAC)
	message(STATUS "Fraunhoffer AAC codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_FDK_AAC)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/fdk_aac.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/fdk_aac.hxx)
else()
	message(STATUS "Fraunhoffer AAC codec disabled")
endif()
if (WITH_FLAC)
	message(STATUS "FLAC codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_FLAC)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/flac.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/flac.hxx)
else()
	message(STATUS "FLAC codec disabled")
endif()
if (WITH_MP3)
	message(STATUS "MP3 codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_MP3)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/mp3.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/mp3.hxx)
else()
	message(STATUS "MP3 codec disabled")
endif()
if (WITH_OPUS)
	message(STATUS "OPUS codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_OPUS)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/opus.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/opus.hxx)
else()
	message(STATUS "OPUS codec disabled")
endif()
if (WITH_VORBIS)
	message(STATUS "VORBIS codec enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_VORBIS)
	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/vorbis.cxx)
	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/vorbis.hxx)
else()
	message(STATUS "VORBIS codec disabled")
endif()

target_sources(StormByte-VideoConvert-library PRIVATE ${VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES})