# Encoder support
# Video
option(WITH_AV1				"Enable AV1 encoder"					ON)
option(WITH_H264			"Enable H264 encoder"					ON)
option(WITH_H265			"Enable HEVC/H265 encoder"				ON)
option(WITH_MPEG2			"Enable MPEG2 encoder"					ON)
option(WITH_RAV1E			"Enable RAV1E encoder"					ON)
option(WITH_VPX				"Enable VPX encoder"					ON)
option(WITH_XVID			"Enable XVID encoder"					ON)
# Audio
option(WITH_AAC				"Enable AAC encoder"					ON)
option(WITH_AC3				"Enable AC3 encoder"					ON)
option(WITH_DTS				"Enable DTS encoder"					ON)
option(WITH_EAC3			"Enable EAC3 encoder"					ON)
option(WITH_FDK_AAC			"Enable FDK_AAC encoder"				ON)
option(WITH_FLAC			"Enable FLAC encoder"					ON)
option(WITH_MP3				"Enable MP3 encoder"					ON)
option(WITH_OPUS			"Enable OPUS encoder"					ON)
option(WITH_VORBIS			"Enable VORBIS encoder"					ON)

# Codec configuration
if (WITH_AV1)
	message("-- Enabling AV1 encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AV1)
endif()
if (WITH_H264)
	message("-- Enabling H264 encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_H264)
endif()
if (WITH_H265)
	message("-- Enabling HEVC/H265 encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_H265)
endif()
if (WITH_MPEG2)
	message("-- Enabling MPEG2 encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_MPEG2)
endif()
if (WITH_RAV1E)
	message("-- Enabling RAV1E encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_RAV1E)
endif()
if (WITH_VPX)
	message("-- Enabling VPX encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_VPX)
endif()
if (WITH_XVID)
	message("-- Enabling XVID encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_XVID)
endif()
if (WITH_AAC)
	message("-- Enabling AAC encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AAC)
endif()
if (WITH_AC3)
	message("-- Enabling AC-3 encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AC3)
endif()
if (WITH_DTS)
	message("-- Enabling DTS encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_DTS)
endif()
if (WITH_EAC3)
	message("-- Enabling EAC-3 encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_EAC3)
endif()
if (WITH_FDK_AAC)
	message("-- Enabling Fraunhoffer AAC encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_FDK_AAC)
endif()
if (WITH_FLAC)
	message("-- Enabling FLAC encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_FLAC)
endif()
if (WITH_MP3)
	message("-- Enabling MP3 encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_MP3)
endif()
if (WITH_OPUS)
	message("-- Enabling OPUS encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_OPUS)
endif()
if (WITH_VORBIS)
	message("-- Enabling VORBIS encoder")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_VORBIS)
endif()
