# Encoder support
# Video
option(WITH_AV1				"Enable AV1 encoder"					ON)
option(WITH_H264			"Enable H264 encoder"					ON)
option(WITH_H265			"Enable HEVC/H265 encoder"				ON)
option(WITH_MPEG2			"Enable MPEG2 encoder"					ON)
option(WITH_RAV1E			"Enable RAV1E encoder"					ON)
option(WITH_VPX				"Enable VPX encoder"					ON)
option(WITH_XVID			"Enable XVID encoder"					ON)
# Audio
option(WITH_AAC				"Enable AAC encoder"					ON)
option(WITH_AC3				"Enable AC3 encoder"					ON)
option(WITH_DTS				"Enable DTS encoder"					ON)
option(WITH_EAC3			"Enable EAC3 encoder"					ON)
option(WITH_FDK_AAC			"Enable FDK_AAC encoder"				ON)
option(WITH_FLAC			"Enable FLAC encoder"					ON)
option(WITH_MP3				"Enable MP3 encoder"					ON)
option(WITH_OPUS			"Enable OPUS encoder"					ON)
option(WITH_VORBIS			"Enable VORBIS encoder"					ON)

# Codec configuration
# Video
if (WITH_AV1)
	message(STATUS "AV1 encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AV1)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/av1.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/av1.hxx)
else()
	message(STATUS "AV1 encoder disabled")
endif()
if (WITH_H264)
	message(STATUS "H264 encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_H264)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h264.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h264.hxx)
else()
	message(STATUS "H264 encoder disabled")
endif()
if (WITH_H265)
	message(STATUS "HEVC/H265 encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_H265)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h265.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/h265.hxx)
else()
	message(STATUS "HEVC/H265 encoder disabled")
endif()
if (WITH_MPEG2)
	message(STATUS "MPEG2 encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_MPEG2)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/mpeg2.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/mpeg2.hxx)
else()
	message(STATUS "MPEG2 encoder disabled")
endif()
if (WITH_RAV1E)
	message(STATUS "RAV1E encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_RAV1E)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/rav1e.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/rav1e.hxx)
else()
	message(STATUS "RAV1E encoder disabled")
endif()
if (WITH_VPX)
	message(STATUS "VPX encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_VPX)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/vpx.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/vpx.hxx)
else()
	message(STATUS "VPX encoder disabled")
endif()
if (WITH_XVID)
	message(STATUS "XVID encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_XVID)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/xvid.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/xvid.hxx)
else()
	message(STATUS "XVID encoder disabled")
endif()

# Audio
if (WITH_AAC)
	message(STATUS "AAC encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AAC)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/aac.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/aac.hxx)
else()
	message(STATUS "AAC encoder disabled")
endif()
if (WITH_AC3)
	message(STATUS "AC-3 encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AC3)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/ac3.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/ac3.hxx)
	else()
	message(STATUS "AC-3 encoder disabled")
endif()
if (WITH_DTS)
	message(STATUS "DTS encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_DTS)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/dts.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/dts.hxx)
else()
	message(STATUS "DTS encoder disabled")
endif()
if (WITH_EAC3)
	message(STATUS "EAC-3 encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_EAC3)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/eac3.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/eac3.hxx)
else()
	message(STATUS "EAC-3 encoder disabled")
endif()
if (WITH_FDK_AAC)
	message(STATUS "Fraunhoffer AAC encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_FDK_AAC)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/fdk_aac.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/fdk_aac.hxx)
else()
	message(STATUS "Fraunhoffer AAC encoder disabled")
endif()
if (WITH_FLAC)
	message(STATUS "FLAC encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_FLAC)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/flac.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/flac.hxx)
else()
	message(STATUS "FLAC encoder disabled")
endif()
if (WITH_MP3)
	message(STATUS "MP3 encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_MP3)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/mp3.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/mp3.hxx)
else()
	message(STATUS "MP3 encoder disabled")
endif()
if (WITH_OPUS)
	message(STATUS "OPUS encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_OPUS)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/opus.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/opus.hxx)
else()
	message(STATUS "OPUS encoder disabled")
endif()
if (WITH_VORBIS)
	message(STATUS "VORBIS encoder enabled")
	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_VORBIS)
	list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/vorbis.cxx)
	list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/audio/vorbis.hxx)
else()
	message(STATUS "VORBIS encoder disabled")
endif()

target_sources(StormByte-VideoConvert-library PRIVATE ${VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES})