# Encoder support
# Video

# Codec configuration
# Video
#if (WITH_AV1)
#	message(STATUS "AV1 codec enabled")
#	target_compile_definitions(StormByte-VideoConvert-library PRIVATE ENABLE_AV1)
#	#list(APPEND VIDEOCONVERT_LIBRARY_SOURCE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/av1.cxx)
#	#list(APPEND VIDEOCONVERT_LIBRARY_INCLUDE_EXTRA_FILES ${PROJECT_LIBRARY_DIR}/media/codec/video/av1.hxx)
#else()
#	message(STATUS "AV1 codec disabled")
#endif()
option(ENABLE_DAV1D	 		"Enable DAV1D AV1 decoder"		ON)
option(ENABLE_LIBAOM 		"Enable AV1 libAOM"				ON)
option(ENABLE_CUDA 			"Enable CUDA decoding" 			ON)
option(ENABLE_OPENH264 		"Enable OpenH264" 				ON)
option(ENABLE_LIBVPX 		"Enable LibVPX" 				ON)
option(ENABLE_FDK 			"Enable FDK" 					ON)
option(ENABLE_LIBOPUS 		"Enable LibOpus" 				ON)
option(ENABLE_LIBVORBIS 	"Enable LibVorbis" 				ON)
option(ENABLE_RAV1E 		"Enable RAV1E" 					ON)
option(ENABLE_SVT_AV1 		"Enable SVT AV1" 				ON)
option(ENABLE_NVENC 		"Enable NVEnc" 					ON)
option(ENABLE_X264 			"Enable x264" 					ON)
option(ENABLE_X265 			"Enable x265" 					ON)
option(ENABLE_XVID 			"Enable XVID" 					ON)
option(ENABLE_TWOLAME 		"Enable TwoLame MP2 encoder" 	ON)
option(ENABLE_LAME 			"Enable Lame MP3 encoder" 		ON)
option(ENABLE_LIBOPUS 		"Enable LibOpus" 				ON)
option(ENABLE_LIBVORBIS 	"Enable LibVorbis" 				ON)
option(ENABLE_WEBP 			"Enable WebP" 					ON)